In [1]:
#perceptron

In [2]:
import os
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
%matplotlib inline
os.getcwd(),os.listdir()


('C:\\Users\\kochallibrhm\\Desktop\\Ders\\Görüntü İşleme\\week_09',
 ['.ipynb_checkpoints',
  'debug.log',
  'kordon.jpg',
  'penguins.jfif',
  'README.MD',
  'week9.ipynb'])

In [37]:
class Perceptron(object):
    """Implements a perceptron network"""
        
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr

    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a

    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

# 1. PERCEPTRON CLASS TANIMININDA VAR OLAN FONKSIYONLARI KISACA TANITINIZ.

"""
    Cevap:


    1 - def __init__(self, input_size, lr=1, epochs=10)  

            Bu fonskiyon bizim "constructor"ımız. "epochs" ve "lr" değişkenleri default olarak set edilmiş
        ve oluşturulan nesneye atanıyor. W parametresine sıfırlardan oluşan bir dizi set ediyoruz. Girdi boyutuna artı bir
        eklememizin nedeni, ağırlık vektörüne sapmayı dahil etmektir. 
        
        Öğrenme Hızı(LR): Her bir ağırlık her güncellendiğinde düzeltilen miktarı sınırlamak için kullanılır. 
        Epochs: Ağırlık güncellenirken pratik verilerinin kaç kez çalıştırılacağı.


    2 - def activation_fn(self, x) 
            
            Bu fonksiyon üretilen x değerini kontrol ediyor. X sıfırdan büyükse 1 değilse 0 döndürüyor. 
        Bu şekilde, Perceptron, iki sınıfı ayırmak için doğrusal bir denklemin (benzer veya hiper düzlem)
        kullanılabileceği iki sınıflı (0 ve 1) problemler için bir sınıflandırma yapıyor.
    
    
    3 - def predict(self, x)
            
            Gelen x değerinin 0. indexine 1'i insert ediyor ve daha sonra bu değeri yukarıda oluşturduğu W'nin
        transpozesi ile dot product işlemine tabi tutuyor ve tek bir çıktı elde ediyor. Buradan çıkan sonucu da 
        def activation_fn fonksiyonuna gönderiyor buradan gelen sonucu return ediyor.
    
    
    4 - def fit(self, X, d)
            
            X'in içerisindeki veri kadar dönüp e = d - y formülü kullanarak error u buluyoruz ve ardından
         w <-- w + n . e . x formülünü uyguluyoruz.


"""

In [50]:
# 2. XOR İÇİN VERİLERİ DEĞİŞTİRİP ÇALIŞMASINI GÖZLEMLEYİNİZ.

""" Cevap: """

d_2 = np.array([0, 1, 1, 0]) # XOR

perceptron_2 = Perceptron(input_size=2)
perceptron_2.W

array([0., 0., 0.])

In [51]:
perceptron_2.fit(X, d_2)
print(perceptron_2.W)      """  XOR İÇİN SONUÇTA GÖRÜLDÜĞÜ ÜZERE [ 0. -1.  0.] değerleri karşımıza çıkmakta """

[ 0. -1.  0.]


In [ ]:
# 4. BU MODELIN HATASI NASIL ELDE EDILIR, KENDI ÇÖZÜMÜNÜZÜ/YORUMUNUZU YAZINIZ.

"""
    Cevap:
        
            Hatayı istenen çıktı ile tahmin edilen çıktı arasındaki farktan yararlanarak bulabiliriz. Bu fark bize tahminimizde
        ne kadarlık bir sapma yapmış olduğumuzu gösterecektir. Yapılan hatanın boyutu da burdan ölçülebilir. Ya da bu farkı
        direkt olarak hata diye tanımlayabiliriz.
        

"""

In [21]:
mp = Perceptron(5)
mp.W

array([0., 0., 0., 0., 0., 0.])

In [30]:
mp.activation_fn(10), mp.activation_fn(-10)


(1, 0)

In [25]:
x = np.asarray([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [26]:
mp.predict(x)

1

In [28]:
x = np.asarray([-10, -2, -30, 4, -50])
mp.predict(x)

1

In [33]:
if __name__ == '__main__':
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [34]:
d = np.array([0, 0, 0, 1])
d

array([0, 0, 0, 1])

In [39]:
perceptron = Perceptron(input_size=2)
perceptron.W

array([0., 0., 0.])

In [40]:
perceptron.fit(X, d)
print(perceptron.W)

[-3.  2.  1.]
